version: '3.1'

services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        hostname: rabbitmq
        ports:
            - '15672:15672'
            - '5672:5672'
        environment:
            RABBITMQ_ERLANG_COOKIE: erlang_cookie
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq
            RABBITMQ_DEFAULT_VHOST: '/'

    mongodb:
        container_name: mongodb
        image: mongo:latest
        ports:
            - '27017:27017'
            - '27018:27018'
        volumes: 
            - /db-data:/data/db
